/**
 * Static app map embedded into the chat system prompt.
 *
 * `specs/APP_MAP.md` is a skeleton-not-skin layout map: the nav chrome, the
 * sections, and what each analytics tab plots plus its controls — enough for
 * Capy to answer "where do I import data?" / "where's my monthly budget?" with
 * the real path instead of a confident guess. Chat-only: import and enrich are
 * headless pipelines nobody asks for directions, so they don't carry it.
 *
 * Sourced from `specs.generated.ts` (regenerated by `scripts/generate-specs.ts`
 * on every build). Edit the markdown, not this string.
 */

import { SPECS } from "../specs.generated"

export const APP_MAP = SPECS["APP_MAP.md"] ?? ""
