/**
 * Static app map embedded into the chat system prompt so wayfinding
 * questions get the real layout (`specs/APP_MAP.md`).
 *
 * Sourced from `specs.generated.ts` (regenerated by `scripts/generate-specs.ts`
 * on every build). Edit the markdown, not this string.
 */

import { SPECS } from "../specs.generated"

export const APP_MAP = SPECS["APP_MAP.md"] ?? ""
