/**
 * Shared app-knowledge brief embedded into every intelligence entry point.
 *
 * `specs/APP_KNOWLEDGE.md` is a tight, purpose-built doc that teaches Capy
 * the transaction model, the analytics surface, who the user is, and what
 * Capy's job is — the always-on common ground for chat, import, and enrich.
 * Each prompt layers its own entry-point-specific instructions on top.
 *
 * Sourced from `specs.generated.ts` (regenerated by `scripts/generate-specs.ts`
 * on every build). Edit the markdown, not this string.
 */

import { SPECS } from "../specs.generated"

export const APP_KNOWLEDGE = SPECS["APP_KNOWLEDGE.md"] ?? ""
