/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetIndexRouteImport } from './routes/budget/index'
import { Route as BudgetCategoriesRouteImport } from './routes/budget/categories'
import { Route as BudgetAccountAccountIdRouteImport } from './routes/budget/account.$accountId'

const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetIndexRoute = BudgetIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudgetRoute,
} as any)
const BudgetCategoriesRoute = BudgetCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BudgetRoute,
} as any)
const BudgetAccountAccountIdRoute = BudgetAccountAccountIdRouteImport.update({
  id: '/account/$accountId',
  path: '/account/$accountId',
  getParentRoute: () => BudgetRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetRouteWithChildren
  '/budget/categories': typeof BudgetCategoriesRoute
  '/budget/': typeof BudgetIndexRoute
  '/budget/account/$accountId': typeof BudgetAccountAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget/categories': typeof BudgetCategoriesRoute
  '/budget': typeof BudgetIndexRoute
  '/budget/account/$accountId': typeof BudgetAccountAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRouteWithChildren
  '/budget/categories': typeof BudgetCategoriesRoute
  '/budget/': typeof BudgetIndexRoute
  '/budget/account/$accountId': typeof BudgetAccountAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/budget/categories'
    | '/budget/'
    | '/budget/account/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/budget/categories' | '/budget' | '/budget/account/$accountId'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/budget/categories'
    | '/budget/'
    | '/budget/account/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget/': {
      id: '/budget/'
      path: '/'
      fullPath: '/budget/'
      preLoaderRoute: typeof BudgetIndexRouteImport
      parentRoute: typeof BudgetRoute
    }
    '/budget/categories': {
      id: '/budget/categories'
      path: '/categories'
      fullPath: '/budget/categories'
      preLoaderRoute: typeof BudgetCategoriesRouteImport
      parentRoute: typeof BudgetRoute
    }
    '/budget/account/$accountId': {
      id: '/budget/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/budget/account/$accountId'
      preLoaderRoute: typeof BudgetAccountAccountIdRouteImport
      parentRoute: typeof BudgetRoute
    }
  }
}

interface BudgetRouteChildren {
  BudgetCategoriesRoute: typeof BudgetCategoriesRoute
  BudgetIndexRoute: typeof BudgetIndexRoute
  BudgetAccountAccountIdRoute: typeof BudgetAccountAccountIdRoute
}

const BudgetRouteChildren: BudgetRouteChildren = {
  BudgetCategoriesRoute: BudgetCategoriesRoute,
  BudgetIndexRoute: BudgetIndexRoute,
  BudgetAccountAccountIdRoute: BudgetAccountAccountIdRoute,
}

const BudgetRouteWithChildren =
  BudgetRoute._addFileChildren(BudgetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
