/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BudgetSettingsRouteImport } from './routes/budget/settings'
import { Route as BudgetHelpRouteImport } from './routes/budget/help'
import { Route as BudgetShellRouteImport } from './routes/budget/_shell'
import { Route as BudgetShellIndexRouteImport } from './routes/budget/_shell/index'
import { Route as BudgetShellImportRouteImport } from './routes/budget/_shell/import'
import { Route as BudgetShellCategoriesRouteImport } from './routes/budget/_shell/categories'
import { Route as BudgetShellAccountAccountIdRouteImport } from './routes/budget/_shell/account.$accountId'

const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetSettingsRoute = BudgetSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BudgetRoute,
} as any)
const BudgetHelpRoute = BudgetHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => BudgetRoute,
} as any)
const BudgetShellRoute = BudgetShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => BudgetRoute,
} as any)
const BudgetShellIndexRoute = BudgetShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BudgetShellRoute,
} as any)
const BudgetShellImportRoute = BudgetShellImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => BudgetShellRoute,
} as any)
const BudgetShellCategoriesRoute = BudgetShellCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => BudgetShellRoute,
} as any)
const BudgetShellAccountAccountIdRoute =
  BudgetShellAccountAccountIdRouteImport.update({
    id: '/account/$accountId',
    path: '/account/$accountId',
    getParentRoute: () => BudgetShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/budget': typeof BudgetShellRouteWithChildren
  '/budget/help': typeof BudgetHelpRoute
  '/budget/settings': typeof BudgetSettingsRoute
  '/budget/categories': typeof BudgetShellCategoriesRoute
  '/budget/import': typeof BudgetShellImportRoute
  '/budget/': typeof BudgetShellIndexRoute
  '/budget/account/$accountId': typeof BudgetShellAccountAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/budget': typeof BudgetShellIndexRoute
  '/budget/help': typeof BudgetHelpRoute
  '/budget/settings': typeof BudgetSettingsRoute
  '/budget/categories': typeof BudgetShellCategoriesRoute
  '/budget/import': typeof BudgetShellImportRoute
  '/budget/account/$accountId': typeof BudgetShellAccountAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/budget': typeof BudgetRouteWithChildren
  '/budget/_shell': typeof BudgetShellRouteWithChildren
  '/budget/help': typeof BudgetHelpRoute
  '/budget/settings': typeof BudgetSettingsRoute
  '/budget/_shell/categories': typeof BudgetShellCategoriesRoute
  '/budget/_shell/import': typeof BudgetShellImportRoute
  '/budget/_shell/': typeof BudgetShellIndexRoute
  '/budget/_shell/account/$accountId': typeof BudgetShellAccountAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/budget'
    | '/budget/help'
    | '/budget/settings'
    | '/budget/categories'
    | '/budget/import'
    | '/budget/'
    | '/budget/account/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/budget'
    | '/budget/help'
    | '/budget/settings'
    | '/budget/categories'
    | '/budget/import'
    | '/budget/account/$accountId'
  id:
    | '__root__'
    | '/'
    | '/budget'
    | '/budget/_shell'
    | '/budget/help'
    | '/budget/settings'
    | '/budget/_shell/categories'
    | '/budget/_shell/import'
    | '/budget/_shell/'
    | '/budget/_shell/account/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BudgetRoute: typeof BudgetRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget/settings': {
      id: '/budget/settings'
      path: '/settings'
      fullPath: '/budget/settings'
      preLoaderRoute: typeof BudgetSettingsRouteImport
      parentRoute: typeof BudgetRoute
    }
    '/budget/help': {
      id: '/budget/help'
      path: '/help'
      fullPath: '/budget/help'
      preLoaderRoute: typeof BudgetHelpRouteImport
      parentRoute: typeof BudgetRoute
    }
    '/budget/_shell': {
      id: '/budget/_shell'
      path: ''
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetShellRouteImport
      parentRoute: typeof BudgetRoute
    }
    '/budget/_shell/': {
      id: '/budget/_shell/'
      path: '/'
      fullPath: '/budget/'
      preLoaderRoute: typeof BudgetShellIndexRouteImport
      parentRoute: typeof BudgetShellRoute
    }
    '/budget/_shell/import': {
      id: '/budget/_shell/import'
      path: '/import'
      fullPath: '/budget/import'
      preLoaderRoute: typeof BudgetShellImportRouteImport
      parentRoute: typeof BudgetShellRoute
    }
    '/budget/_shell/categories': {
      id: '/budget/_shell/categories'
      path: '/categories'
      fullPath: '/budget/categories'
      preLoaderRoute: typeof BudgetShellCategoriesRouteImport
      parentRoute: typeof BudgetShellRoute
    }
    '/budget/_shell/account/$accountId': {
      id: '/budget/_shell/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/budget/account/$accountId'
      preLoaderRoute: typeof BudgetShellAccountAccountIdRouteImport
      parentRoute: typeof BudgetShellRoute
    }
  }
}

interface BudgetShellRouteChildren {
  BudgetShellCategoriesRoute: typeof BudgetShellCategoriesRoute
  BudgetShellImportRoute: typeof BudgetShellImportRoute
  BudgetShellIndexRoute: typeof BudgetShellIndexRoute
  BudgetShellAccountAccountIdRoute: typeof BudgetShellAccountAccountIdRoute
}

const BudgetShellRouteChildren: BudgetShellRouteChildren = {
  BudgetShellCategoriesRoute: BudgetShellCategoriesRoute,
  BudgetShellImportRoute: BudgetShellImportRoute,
  BudgetShellIndexRoute: BudgetShellIndexRoute,
  BudgetShellAccountAccountIdRoute: BudgetShellAccountAccountIdRoute,
}

const BudgetShellRouteWithChildren = BudgetShellRoute._addFileChildren(
  BudgetShellRouteChildren,
)

interface BudgetRouteChildren {
  BudgetShellRoute: typeof BudgetShellRouteWithChildren
  BudgetHelpRoute: typeof BudgetHelpRoute
  BudgetSettingsRoute: typeof BudgetSettingsRoute
}

const BudgetRouteChildren: BudgetRouteChildren = {
  BudgetShellRoute: BudgetShellRouteWithChildren,
  BudgetHelpRoute: BudgetHelpRoute,
  BudgetSettingsRoute: BudgetSettingsRoute,
}

const BudgetRouteWithChildren =
  BudgetRoute._addFileChildren(BudgetRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BudgetRoute: BudgetRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
